### ISSUE TITLE
Mejora en el orden de los resultados

### ISSUE THREAD

**Issue by Meliborque** [efahnle/hacemosnumeros#1]
Cuando se genera una división de gastos, se muestran intercalados los items de paga/recibe. 
Se propone agrupar los montos que se reciben y que se deben pagar. Y de la misma forma ordenar el mensaje de whatsapp. 
 
![image](https://github.com/user-attachments/assets/17a3125a-cc59-42bf-888c-bae03a9fa119)
![image](https://github.com/user-attachments/assets/24bf79d5-8ffb-470e-9c8d-258b1a4d5ad6)

**Comment by efahnle** [comment]
# Cambio en orden
![image](https://github.com/user-attachments/assets/87cb9fe7-6939-4d91-a7cf-f6f8520f0696)

## Antes
![image](https://github.com/user-attachments/assets/ac026ee3-7fcb-487a-949e-424350c86fbc)



## Despues
![image](https://github.com/user-attachments/assets/9d1778df-aca4-42e1-9031-52f1a79d28a8)

# Compartir por Whatsapp

## Editado
![image](https://github.com/user-attachments/assets/6cfadb7e-cd32-406e-9afc-cd8616e6b2c8)



Gracias! <3

**Comment by Meliborque** [comment]
Quedó muy bien!
