### ISSUE TITLE
Mejora en el orden de juntadas anteriores

### ISSUE THREAD

**Issue by Meliborque** [efahnle/hacemosnumeros#2]
Al visualizar las juntadas anteriores, se muestran de la mas antigua primero y las mas recientes al final. 
Se propone invertir el orden para facilitarle al usuario la edición de su juntada mas reciente. 

![image](https://github.com/user-attachments/assets/3a21f389-2f07-4918-864f-16b01c0fe3df)

**Comment by efahnle** [comment]
Más reciente arriba
![image](https://github.com/user-attachments/assets/01ebfd6c-e4ad-46c2-b903-8a11cb259a3a)

Las últimas juntadas se ingresan arriba
![image](https://github.com/user-attachments/assets/39153617-81a3-4555-aeec-1d427547d1df)

El comportamiento de los indices no se modifico, solo la tabla se muestra en orden inverso. La primer juntada (Cena en lo de eric) que ahora está abajo de todo mantiene indice 0
![image](https://github.com/user-attachments/assets/4110a41c-a320-4aae-95e0-2c24825d150b)
